Add Galactic Machine Frame blockmodel
Divine-Journey-2/Divine-Journey-2 pull request #1082
Opened 2023-12-06 17:54 UTC by KleinGrrmpf

This adds the galactic machine frame as a blockmodel to make it more in line with the other custom machine frames. I tried to stay as close to the pixelated item texture and I did use GC textures for this. Specifically the "machine_side", "machine", and "oxygen_storage_module_full" (where I cut out and rotated the oxygen bar and turned it into a deeper blue with more saturation to match the blue box on the 2D item) were used.

2023-12-06 18:11 UTC, WaitingIdly requested changes

2023-12-06 18:13 UTC, KleinGrrmpf commented on overrides/resources/contenttweaker/blockstates/galactic_machine_frame.json
> +      "side": "contenttweaker:blocks/galactic_machine_fram_side",
Goddammit

2023-12-19 08:30 UTC, KleinGrrmpf commented
If there is anything else missing, let me know!

2024-02-22 19:49 UTC, WaitingIdly approved these changes

2024-02-22 19:49 UTC, merged