Quest stuff 11/28
Divine-Journey-2/Divine-Journey-2 pull request #827
Opened 2022-11-29 03:25 UTC by King65868

2022-11-29 09:12 UTC, WaitingIdly requested changes

2022-11-30 02:31 UTC, WaitingIdly commented on overrides/config/betterquesting/DefaultQuests.json
> +          "desc:8": "Craft a Golden Club! You only need one, but you can make more if you want.\n\nBy swinging this in the air it uses up 1 durability to summon Lightning! If you want to use it for a
you made them all uppercase. the summoned object "lightning" is not a proper name, it should be lowercase.

2022-11-30 02:31 UTC, WaitingIdly commented on overrides/config/betterquesting/DefaultQuests.json
> +          "desc:8": "Craft an Ultimate Energy Cube! For now, this will be your best way of storing energy! ...But wait until you get into late Mekanism or Draconic."
not asking to revert, just asking to keep EnderIO.

2022-11-30 02:41 UTC, King65868 commented on overrides/config/betterquesting/DefaultQuests.json
> +          "desc:8": "Craft a Golden Club! You only need one, but you can make more if you want.\n\nBy swinging this in the air it uses up 1 durability to summon Lightning! If you want to use it for a
Is that good?

2022-11-30 02:46 UTC, King65868 commented
This should be good now

2022-11-30 06:23 UTC, WaitingIdly approved these changes

2022-11-30 06:25 UTC, WaitingIdly commented on overrides/config/betterquesting/DefaultQuests.json
> +          "desc:8": "Craft an Ultimate Energy Cube! For now, this will be your best way of storing energy! ...But wait until you get into late Mekanism or Draconic."
whoops, missed this: `EnderIO`, not `Enderio`

2022-11-30 06:38 UTC, merged